{
 "title": "dashboard_2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Tentatives de connexion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(user_login_attempts_total{success=\"true\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(user_login_attempts_total{success=\"false\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transitions de statut (5 dernières minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (from_status, to_status) (rate(tasks_status_changes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Répartition par priorité",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (priority) (increase(tasks_created_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tâches créées par minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(tasks_created_total[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}