apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-cm
  namespace: staging
data:
  PORT: "3002"
  DATABASE_URL: "postgresql://taskflow:taskflow@postgres:5432/taskflow"
  REDIS_URL: "redis://redis:6379"
  JWT_SECRET: "dev-jwt-secret-change-in-production"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
